#!/usr/bin/env bash
# Bash script that will display information about subdomains.

func (){
    ip_and_rec=$(dig "$2"."$1" | grep -A1 "ANSWER SECTION" | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $ip_and_rec" | awk '{print "The subdomain "$1" is a "$2" record and points to "$3""}'
}

if [ "$#" -eq 2 ];then
    func "$1" "$2"
elif [ "$#" == 1 ];then
    func "$1" "www"
    func "$1" "lb-01"
    func "$1" "web-01"
    func "$1" "web-02"
fi
