#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl, it
# must return a page that contains the string Hello World!
# As an answer file, write a Bash script that configures a new Ubuntu machine to respect
# above requirements (this script will be run on the server itself)
# You can’t use systemctl for restarting nginx

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page\n" > /var/www/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   root      /var/www/html;
    index index.html index.htm;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
    }

    error_page 404 /404.html;
    location = /404.html{
        root /var/www/html;
        internal;
    }

}" > /etc/nginx/sites-enabled/default

service nginx restart
