#!/usr/bin/env bash
# install and configure HAproxy load balancer

apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y install haproxy=2.6.\*

printf %s "
frontend hbnb_front
        mode http
        bind *:80
        default_backend hbnb_back

backend hbnb_back
        mode http
        balance roundrobin
        cookie SERVERUSED insert indirect nocache
        server 4577-web-01 18.205.96.48:80 check cookie 4577-web-01
        server 4577-web-02 3.231.218.163:80 check cookie 4577-web-02
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy restart
