#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates
# a compressed archive out of it.
now="$(date '+%d-%m-%Y')"
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czf "$now".tar.gz backup.sql
