#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.

# cat /etc/passwd | cut -d: -f1,3,6 don't work with shellcheck

while read -r i; do
    echo "${i}" | cut -d: -f1,3,6; 
done < /etc/passwd
