#!/usr/bin/env bash
# Your machine has an SSH configuration file for the local SSH client
# let’s configure it to our needs so that
# you can connect to a server without typing a password.

Host 4577-web-01
 HostName 18.205.96.48
 User ubuntu
 IdentityFile ~/.ssh/school
